baseURL = "https://blog.blackpiratex.com"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Blog By BlackPirateX"
description = "Blog By BlackPirateX"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"
[taxonomies]
  category = 'categories'
    tag = 'tags'

# Author config
[author]
  name = "BlackPirateX"
  email = "hi@sudipx.in"
  link = "https://blackpiratex.com"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    name = "Main Website"
    url = "https://blackpiratex.com"
    title = "https://blackpiratex.com"
    pre = ""
    post = ""
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    # you can add extra information after the name (HTML format is supported), such as icons
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "Tags"
    pre = ""
    post = ""

    url = "/tags/"
    title = ""

  [[menu.main]]
    weight = 3
    identifier = "gallery"
    name = "Gallery"
    pre = ""
    post = ""

    url = "https://gallery.blackpiratex.com"
    title = "Go to my photo gallery"

  [[menu.main]]
    weight = 4
    identifier = "rss"
    name = "Subscribe via RSS"
    pre = ""
    post = ""

    url = "/index.xml"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false


[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "dark"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt NEW | 0.2.0 date format
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "Blog By BlackPirateX"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Blog By BlackPirateX"
  # website images for Open Graph and Twitter Cards
  images = [""]

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = ""
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Blog By BlackPirateX"
      # subtitle shown in home page
      subtitle = "A place for me to write down my thoughts, rants, reviews and study notes."
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false


      [sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5



  [params.search]
  enable = true
  # type of search engine ["lunr", "algolia"]
  type = "algolia"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = "Search on the website"
  #  max number of results length
  maxResultLength = 10
  #  snippet length of the result
  snippetLength = 30
  #  HTML tag name of the highlight part in results
  highlightTag = "em"
  #  whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = "blog"
    appID = "1BK9CWUE1P"
    searchKey = "adb8fc3e8b560f157f55777ba0895c89"

[outputs]
	home = [ "HTML", "JSON", "RSS"]
	page = [ "HTML"]


