# netlify.toml

[build]
  # 1. Install dependencies
  # 2. Run the script to fetch comments
  # 3. Run the Hugo build
  command = "npm install && node scripts/fetch-comments.js && hugo"
  
  # Hugo's default publish directory is "public"
  publish = "public"

  # The functions directory is now defined here
  functions = "netlify/functions/"

# This section now correctly configures your specific function trigger
# without conflicting with other settings.
[[functions]]
  # The function file to use, relative to the functions directory.
  # This corresponds to `netlify/functions/add-comment.js`
  function = "add-comment"

  # The event that triggers the function. This will fire for ANY form submission.
  event = "submission-created"
  
  # We specify the bundler here to ensure it's applied to this function.
  node_bundler = "esbuild"
