# netlify.toml

[build]
  # 1. Install dependencies
  # 2. Run the script to fetch comments
  # 3. Run the Hugo build
  command = "npm install && node scripts/fetch-comments.js && hugo"
  
  # Hugo's default publish directory is "public"
  publish = "public"

# Global settings for all of your serverless functions.
[functions]
  # The directory where your serverless functions live.
  directory = "netlify/functions/"
  
  # This bundler will be used for all functions.
  node_bundler = "esbuild"
